education_details = {  
                     'Borçlar Hukuku': 'Bu derste genel hukumler çerçevesinde haklarin ve borçlarin meydana gelişi, borç ilişkisi ve sorumluluk kavrami, hukukî yukumluluk, kulfet ve talep hakki kavramlari, hukukî işlemler ve borç kaynaklari kapsaminda sözleşmelerin kurulmasi, sözleşmeden doğan sorumluluk, haksiz fillerden doğan sorumluluk, sebepsiz zenginleşme ve taraf ehliyeti, sözleşme serbestisi ve sinirlandirilmasi, irade bozukluklari ve iradenin sakatlanmasi, kusursuz sorumluluk, borçlarin hukumleri ve sona ermeleri gibi konular incelenmektedir. Dersin sonunda öğrenci, hukukî işlemlerin etkilerini analiz edebilme, problem çözme ve hukuki yorum yapabilme yeteneğini kazanmaktadir.'
, 
                     
                     'Temel Sigortacilik': 'Bu derste; sigortaciliğa genel giriş, Turkiyede sigortaciliğin gelişimi, sigortacilik ile ilgili temel tanimlar ve bilgiler, genel sigortacilik prensipleri işlenmektedir. Ayrica sigortaciliğin tarihsel gelişimi de detaylandirilmaktadir. Genel olarak sigortanin turlerine de değinilmektedir.'
, 
                     
                     'Reasurans Teknikleri': "Genel olarak reasurans, İhtiyari Reasurans, Böluşmeli - Otomatik Reasurans anlaşmalari; Kotpar anlaşmalari, Eksedan anlaşmalari, İhtiyari anlaşmalar, Kotpar - Eksedan karişimi anlaşmalar, Böluşmeli - Eksedan karişimi anlaşmalar, Böluşmeli - Otomatik reasurans anlaşmasinin ortak hukumleri. Böluşmesiz Reasurans anlaşmalari; Hasar Fazlasi Reasurans, Hasar Orani Reasurans. Pool Anlaşmalari, Reasurans Uygulamalari."
, 
                     'Matematik': 'Fonksiyon dizileri, serileri ve yakinsaklik testleri; sonsuz seriler ve yakinsaklik testleri; kuvvet serileri ve Taylor teoremi, fonksiyonlar; limit ve sureklilik; turev; turev uygulamalari: uç değerler, ortalama değer teoremi ve uygulamalari, fonksiyon grafiklerinin çizimi; logaritmik, ustel, hiperbolik fonksiyonlar; ektremum ve bağil ekstremum uygulamalari.'
                     'İntegral kavrami; integral alma yöntemleri: değişken değiştirme, parçali integral, trigonometrik ve hiperbolik değişken değiştirme, rasyonel ve irrasyonel ve trigonometrik ifadelerin integralleri, belirli integral ve uygulamalari; doğrusal denklem sistemleri; matris ve matris işlemleri; determinantlar; özdeğer, özvektörler; doğrusal dönuşumler; doğrusal dönuşum matrisleri; köşegenleştirme.'
                     ' Çok değişkenli fonksiyonlar; çok değişkenli fonksiyonlarda limit sureklilik ve turevlenebilme, kismi turevler ve zincir kurali; gradiant ve yönlu turev; çok değişkenli fonksiyonlar için taylor teoremi; çok değişkenli fonksiyonlarin uç değerlerin bulunmasi; çok katli integraller; eğrisel integral ve yuzey integralleri; Green-Stoke teoremi.'
                     'Birinci ve ikinci dereceden diferansiyel denklemler; yuksek dereceden doğrusal diferansiyel denklemler; diferansiyel denklemlerin uygulamalari; doğrusal diferansiyel denklemlerin seriler ile çözumleri; doğrusal diferansiyel denklem sistemleri; Laplace dönuşumleri ve doğrusal diferansiyel denklem sistemlerinin Laplace dönuşumleri ile çözumleri; Fourier serileri ve Fourier analizi.'
,      
                     
                     'Hayat Sigortalari Matematigi': 'Faiz kavrami, iskonto kavrami, basit ve bileşik faiz, bugunku değer ve birikimli değer hesaplamalari, dönem sonu ve dönem başi ödemeli rantlar, hayat tablolari, yaşama ve ölme olasiliklari, anlik ölum orani, rantlar, hayat rantlari konulari ele anlatilmaktadir.'
                     'Cok degerli, rahmetli Feral hocam sayesinde Aktueryal bakis acisi, ve ozellikle hayat aktueryasina dair inanilmaz derinlikli ve faydali bir ders. Hem modelleme teknikleri, hem sektör pratikleri ile derin bir kapsam.',

                     'Hayat Disi Sigortalar Matematigi': 'Prim ilkeleri, deneyim fiyatlandirmasi ve itibar kurami (tam itibar, kismi itibar, buhlman yöntemi, bayesci yaklaşim), Hasar Rezervlerinin Hesaplanma Yöntemleri (Aktueryal Zincirleme Merdiven, Bornhuetter – Ferguson, Cape-Cod, Munich Zinciri, Hasar sikliği ve şiddeti), Stokastik Sureçler (Homojen Poisson sureci, Homojen olmayan Poisson sureci, Rastgele yuruyuş sureci, Bileşik Poisson sureci)',

                     'Risk Analizi ve Aktueryal Modelleme': 'Risk ve fayda kavrami, riskin ölçulmesi, risk ve beklenen getiri, risk ve farklilaştirmasi, yatirim planlamasi, stokastik sureçler (Markov zinciri), senaryo analizi, simulasyon analizi, matlab uygulamalari.'
,

                     'Emeklilik Matematigi': 'Sosyal guvenlik ve emeklilik, yurt içi ve yurt dişi uygulamalari, emeklilik teminatlarinin aktueryal karşiliklari, bunlara ait rezervlerin hesaplanmasi.'
,

                     'Aktueryal Raporlama ve Denetim': 'Aktueryal raporlama kavrami içeriği, finansal rasyolar, finansal analizler, karlilik analizleri, rasyo analizleri, aktueryal varsayimlar, aktueryal denge kavrami, duyarlilik ve senaryo analizleri, Aktueryal denetim esaslari ve uygulamalari.'
,

                     'Simulasyon Teknikleri': 'Simulasyonun avantaj ve dezavantajlari, uygulama alanlari, Simulasyon yazilimlari hakkinda genel bilgi, İstatiksel analiz araçlari, Tesadufi sayi ve tesadufi değişken uretme teknikleri, Kesikli tesadufi sayi uretilmesi, Surekli tesadufi sayi uretilmesi, Simulasyon modelleri için doğrulama ve sağlama, Monte-Carlo simulasyonu, Excel Uygulamalari.'
,
                    
                     'Istatiksel Modelleme': 'İstatistik modelleme kavrami; veri ve değişken yapisi, anakutle örnekleme kavramlari, örnekleme metodlari, istatistiksel modellemede hipotez testleri, doğrusal ve doğrusal olmayan modeller, çok değişkenli istatistiksel modeller, istatistiksel model seçimi, finansal verilere istatistiksel model örnekleri.'
,

                     'Temel Ekonometri': 'Bu dersin amaci, klasik doğrusal, yari logaritmik ve tam logaritmik regresyon modellerini kurabilme ve yorumlayabilme yeterliliği kazandirmaktir. Dönem boyunca istatistik ve ekonometriye ilişkin temel kavramlar, Rassal örneklemenin temel özellikleri Basit doğrusal regresyon modeli varsayimlari, Tahmincilerin Özellikleri, Basit doğrusal regresyon modelinin parametrelerinin EKK yöntemi ile tahmin edilmesi, Ortalamadan farklar ve orijinal gözlemler cinsinden normal denklemlerin bulunuşu, Basit doğrusal regresyon modelinin parametrelerinin yorumlanmasi, E-views Uygulamasi, Basit Korelasyon ve örnek uygulamalar Sira Korelasyon ve örnek uygulamalar, Determinasyon Katsayisi ve örnek uygulamalar Parametre tahminlerinin anlamliliklarinin sinanmasi, Hipotez Testleri Pratik t testi, t testi ve örnek uygulamalar, Modellerde değişken dönuşumu, Korelasyon katsayisisinin anlamliliğinin sinanmasi, Elastikiyet ve örnek uygulamalar, Parametreler için Guven Araliklari, Çok değişkenli doğrusal regresyon modeli analizi; Çok değişkenli doğrusal regresyon modeli varsayimlari, Çok değişkenli modellerde ortalamadan farklar ve orijinal gözlemler cinsinden normal denklemlerin bulunuşu, Çok değişkenli regresyon modeli parametrelerinin yorumlanmasi, Doğrusal olmayan regresyon modellerinin tahmini, Cobb-Douglas tipi uretim fonksiyonu tahmini, Çeşitli ekonometrik fonksiyon kaliplarinin tahmini ve yorumlamasi E-views Uygulamasi, Çeşitli ekonometrik modellere ait elastikiyetler ve eğimler örnek uygulamalar, Ölçek getirisi değişir girdiye getiri işlenecek temel konular arasinda yer alacaktir.'
,
                     'Muhasebe': 'Muhasebe kavrami, mali tablolar, hesap kavrami, muhasebe sureci ve sayisal örnek, muhasebenin temel kavramlari ve genel kabul görmuş muhasebe ilkeleri, stoklarin kapsami, mal alim satimindaki kdv uygulamalari, hazir değerler, menkul kiymetler, alacaklar, duran varliklar, mali borçlar, özkaynaklar, gelirler ve giderler, dönem sonu işlemleri.'
                     'Envanter kavrami, envanter urunleri, envanter ve değerleme, dönem sonunda hesaplarin kapatilmasi ve yeniden açilmasi, kasa hesabinin envanteri, yabanci paralarin envanteri, çek hesaplarinin envanteri, bankalar hesabinin envanteri, hisse senetleri ve tahvillerinin envanteri, alacaklarin envanteri, alacak senetlerinin envanteri, stoklarin envanteri, stok değerleme yöntemleri, stok hareketleri uygulamalari.'
, 
                     'Sigorta Muhasebesi': 'Sigorta muhasebesine giriş. Mali tablolar. Tek duzen hesap plani ve işleyişi. uretim muhasebesi-Prim uretim ve iptal. uretim muhasebesi-kazanilmamiş primler karşiliği. Hayat sigortalari uretim muhasebesi. Sigorta şirketlerinin aracilik işleri. Hayat sigortalari matematik karşiliklar. Devam eden riskler karşiliği. İkramiye ve indirimler karşiliği. Reasurans muhasebesi-uretim.'

, 
                     
                     'Finansal Yönetim': 'Finans fonksiyonu, zaman değeri, finansal analiz, planlama, nakit akimi ve sermaye butçelemesi gibi temel finans yönetimi konularini öğretir.',                      
                     'Finansal Tablolar ve Analizi' : 'Finansal tablo seti nedir, nasil ele alinir, aralarindaki iliskiler nedir konularinde tatmin edici duzeyde gelistirici bir icerigi ile tamamlanir.',
                     'Sigorta Branşlari': 'Yangin, kaza, nakliyat, tekne, muhendislik ve havacilik sigortalari gibi branşlara ilişkin temel bilgiler verilir.', 
                     'Finansal Matematigi': 'Basit faiz, basit iskonto, basit iskonto ile senetlerin denkleştirilmesi, senetlerin denkleştirilmesi, sabit taksitlerle amortisman, basit faizde sabit taksitlerle dönem başi ve dönem sonu plasman, bileşik faiz, bileşik iskonto, bileşik faizde plasman, sabit gelirli rantlar, duzenli değişen gelirli rantlar, sabit taksitli borçlanma, değişen taksitli borçlanmalar.'
                     'Paranin zaman değeri, faiz problemleri, uygulamada karşilaşilan faiz ve iskonto turleri, annuiteler, faiz dönuşum döneminden farkli siklikta yapilabilen ve değişken ödemeli annuiteler, borç ödeme yöntemleri, amortisman ve borç ödeme fonu yöntemleri, yatirim araçlari ve urunlerin değerlemesi.'
,                      
                     'Aktueryal Yazilimlar ve Veri Analizi': 'R ve SAS yazilimlarinin çalişmasi, veri girişi, veri saklama, veriler uzerinde işlemler, matris işlemleri, döngu yapilari ve örnekleri, algoritma tasarimi, grafik çizimleri, matematiksel fonksiyonlar ile işlemler, tanimlayici istatistiklerin elde edilmesi, frekans dağilim grafiklerinin çizimi, frekans ve çapraz tablolarin oluşturulmasi, rastgele sayi uretiminde benzetim uygulamalari.'
,                      

                     'Olasilik I': 'Olasiliğin temel kavramlari, rassal değişkenler, dağilim fonksiyonlari, beklenen değer ve varyans gibi temel istatistiksel hesaplamalar öğretilir.' 
                     'Birleşik dağilimlar, koşullu olasiliklar, sureksiz ve surekli olasilik dağilimlari ve yaklaştirma yöntemleri öğretilir.'
, 
                     'İstatistik': 'İstatistiğin tanimi, konusu, tarihsel gelişimi, önemi ve çeşitli bilim dallari ile ilişkisi, amaci ve turleri, istatistik ile ilgili temel kavramlar, veri kaynaklari ve veri toplama teknikleri (verilerin duzenlenmesi - siniflama, gruplama, seriler - ), grafikler, ortalamalar (merkezi eğilim ölçuleri), değişkenlik ölçuleri, eğiklik ve basiklik ölçuleri, endeksler.'
                     'Örnekleme teorisi, istatistiksel tahmin teorisi, hipotez testleri, ki-kare testi, varyans çözumlemesi ve f testi, regresyon ve korelasyon analizi, zaman serileri çözumlemesi.'
                     
, 


                     'İktisada Giriş': 'Toplumun sinirsiz ihtiyaçlarini sinirli kaynaklarla karşilama sureci. Arz-talep dengesi, piyasa esneklikleri, uretim maliyetleri ve piyasa yapilari gibi temel mikroekonomi konulari işlenir.'                      
                     'Faktör piyasalari, milli gelir, enflasyon, işsizlik, diş ticaret teorileri, ekonomik buyume ve refah gibi temel makroekonomik konular işlenir.'
, 
                     
                     'Mikro ve Makro Ekonomi': 'Mikro ekonomiye giriş, arz ve talebin temelleri, çeşitli piyasa talep eğrileri ve talep ve arz esneklikleri,talep teorisi ve tuketici davranişlari; fayda maksimizasyonu ve tercih, risk ve belirsizlik koşullari altinda talep, uretici davranişlari; tek değişken girdili uretim, iki değişken girdili uretim ve uretim maksimizasyonu, geleneksel maliyet teorisi, modern maliyet teorisi, firma teorisi ve piyasa organizasyonu; tam rekabet piyasasinda fiyat teorisi, tam monopol koşullari altinda fiyat teorisi, piyasa gucu ve fiyatlama, monopolcu rekabet koşullari altinda fiyat teorisi, oligapol piyasalarinda fiyat teorisi, firma ve piyasa teorilerinde son gelişmeler, oyun teorisi ve stratejik davraniş, böluşum teorisi, genel denge ve refah; tam rekabet piyasalarinda marjinal produktivite teorisi, girdi piyasasinda eksik rekabet teorisi, piyasa başarisizliklari; eksik ve asimetrik enformasyon, piyasa sisteminin iyi işlemediği durumlar ve piyasa gucu, dişsalliklar ve kamusal mallar, piyasalarin duzenlenmesi ve özelleştirme.'
                     'Makro ekonomiye giriş, milli gelirle ilgili kavramlar ve milli gelirin ölçulmesi, ekonominin toplam bilançosu, Basit Keynesgil Sistem, Klasik Sistem ve Basit Keynesgil Sistemin Genişletilmesi: para, faiz ve fiyat değişimlerinin milli gelir analizlerinde gözönune alinmasi, para arzi ve para arzinin istikrarliliği sorunu, para talebi, IS-LM eğrileri analizi ve ekonominin talep yanli dengesi, Keynesgil ekonominin kendiliğinden tam istihdama yönelememesi ve Neoklasik oto regulatör olarak reel ankes etkisinin önemi, geleneksel ve modern toplam arz teorileri ve rasyonel bekleyişler altinda ekonomik denge; rasyonel bekleyişler ve modern makro ekonomi; enflasyon, bekleyişler ve uretim- enflasyon analizinin genişletilmesi, eksik istihdam, Philips eğrileri ve Taylor Kurali, Modern Konjonktur Teorileri, yirminci yuzyilda yaşanan buyuk ekonomik krizler, ortadoks ve heterodoks makro ekonomik politika teorileri, kamunun borç sorunu ve çözum yollari, ekonomik istikrar sorunu: yeni makro ekonomik uzlaşma ve enflasyon hedeflemesi, dinamik makro ekonomiye giriş: içsel ve dişsal buyume teorileri, genişletmeler: modern makro ekonomideki gelişmelere toplu bakiş, makro ekonomide yeni uzlaşma, dişa açik makro ekonominin temelleri, açik ekonomide IS-LM-BP analizi, açik ekonomide toplam talep, rasyonel bekleyişler eklentili toplam arz ve toplam talep eğrileri yardimiyla açik ekonomide ekonomik dalgalanmalarin analizi.'
, 
                     'İngilizce ve Meslek İngilizcesi ': 'Başlangiç seviyesinde İngilizce dil bilgisi konulari ve basit cumle yapilarini öğretir. Geniş zaman, olumsuz cumleler ve soru yapilari temel alinir.'
                     'Gelecek zaman, modals gibi gramer konulari ile birlikte konuşma becerilerini geliştirmeye yönelik kelime ve egzersiz çalişmalari içerir.'
                     'Sigortacilik terimleri, temel okuma parçalari, çeviri yöntemleri ve sözlu iletişimi geliştirmeye yönelik mesleki İngilizce konularini işler.'
                     
                     }